# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Python.gitlab-ci.yml

# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
#image: python:$PYTHON_VERSION  # Change image dynamically depending on Python version.

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/topics/caching/
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/

stages:
  - test
  - deploy

# Define a template for testing with different Python versions
.test_template: &test_template
  stage: test
  before_script:
    - python --version
    - python -m pip install --upgrade pip
    - pip install virtualenv

    # Create and activate the virtual environment
    - virtualenv venv
    - source venv/bin/activate
    - pip install poetry
    - poetry install
  script:
    - pytest -v --junitxml=reports/test-results/results.xml
  artifacts:
    paths:
      - reports/test-results/

test:python39:
  <<: *test_template
  image: python:3.9
#  tags:
#    - python39

test:python310:
  <<: *test_template
  image: python:3.10
#  tags:
#    - python310

test:python311:
  <<: *test_template
  image: python:3.11
#  tags:
#    - python311

test:python312:
  <<: *test_template
  image: python:3.12
#  tags:
#    - python312

test:python313:
  <<: *test_template
  image: python:3.13
#  tags:
#    - python313

#pages:
#  script:
#    - pip install sphinx sphinx-rtd-theme
#    - cd doc
#    - make html
#    - mv build/html/ ../public/
#  artifacts:
#    paths:
#      - public
#  rules:
#    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
