repos:
  - repo: local
    hooks:
      - id: export
        name: Export requirements.txt from pyproject.toml
        entry: poetry export -f requirements.txt --output requirements.txt --without-hashes
        language: python
        additional_dependencies:
          - poetry>=1.8.2
          - poetry-plugin-export
        files: ^pyproject\.toml$
        pass_filenames: false
